general:
  project_name: bierrallye
  app_name: Bierreallye Irnfritz
  version: 0.1
production:
  backend_domain: api.bierrallye-irnfritz.at
  frontend_domain: bierrallye-irnfritz.at
  backend_port: 8008
development:
  frontend_domain: localhost:8080
  backend_port: 8008
  server_port: 8000
  frontend_port: 8080