version: '3'

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: backend
      dockerfile: deploy/Dockerfile_development
    volumes:
      - ./backend:/code
    env_file:
      - ./.env
    command: ['./scripts/start.sh']
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  server:
    container_name: ${PROJECT_NAME}_server
    build:
      context: backend
      dockerfile: deploy/Dockerfile_server
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - backend
  frontend:
    container_name: ${PROJECT_NAME}_frontend
    build:
      context: frontend
      dockerfile: deploy/Dockerfile_development
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - './frontend:/app'
      - './frontend/node_modules:/app/node_modules'
    command: ['npm', 'run', 'serve']
    depends_on:
      - backend
      - server