version: '3'

services:
  backend:
    container_name: ${PROJECT_NAME}_backend
    build:
      context: backend
      dockerfile: deploy/Dockerfile_development
    volumes:
      - ./backend:/code
    env_file:
      - ./.env
    command: ['./scripts/start.sh']
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}